# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: DaneSpiritGOD.Suites  # build numbering format
#resources:
  #containers: [ container ]
  #repositories: [ repository ]
#variables: { string: string } | [ variable ]
trigger: 
- master
pr: 
- master
jobs:
  - job: packNugets
    displayName: 'nuget pack and push'
    pool:
      vmImage: 'windows-2019'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      csprojBuildPlatform: 'AnyCPU'
      buildConfiguration: 'Release'
      srcRoot: './'
      nugetSource: 'https://api.nuget.org/v3/index.json'
      shellLink: 'ShellLink'
      propertyStore: 'PropertyStore'

    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        packageType: 'sdk' # Options: runtime, sdk
        version: '3.0.100-preview3-010431'

    - script: dotnet pack -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) $(srcRoot)$(propertyStore)/$(propertyStore).csproj
    - script: dotnet pack -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) $(srcRoot)$(shellLink)/$(shellLink).csproj    

    - script: dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg -k $(nuget.key) -s $(nugetSource) # -n